Drive improvements
The-Knights-of-Ni/PowerPlay pull request #7
Opened 2022-10-14 05:35 UTC by albonec

Deleted duplicate code, lmk if i missed anything unnecessary

2022-10-14 06:22 UTC, arihant2math requested changes
Don't delete the odometery stuff

2022-10-14 06:24 UTC, moogloof commented
keep odometry

2022-10-14 22:26 UTC, moogloof commented
ok good

2022-10-14 23:01 UTC, moogloof approved these changes

2022-10-15 00:08 UTC, arihant2math commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Drive.java
> -    public void moveRightOdometry(double distance) {
This stuff if useful

2022-10-23 00:24 UTC, closed without merging

2022-10-23 00:24 UTC, arihant2math commented
Already merged